# Generated by Django 5.2.9 on 2025-12-04 09:24

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="join_token",
            field=models.CharField(
                default=api.models.generate_class_token, max_length=6, unique=True
            ),
        ),
    ]
