# Generated by Django 5.2.9 on 2025-12-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
